name: API Tests

on:
  workflow_dispatch:
    inputs:
      with_report:
        description: "Generate report?"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.2"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "With report: ${{ github.event.inputs.with_report }}"
          if [ "${{ github.event.inputs.with_report }}" = "true" ]; then
            pytest -m api --testomatio report
          else
            pytest -m api
          fi
        env:
          URL: ${{ secrets.URL }}
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
          TESTOMATIO: ${{ secrets.TESTOMATIO }}
