name: UI Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Choose a browser"
        required: true
        default: "chromium"
        type: choice
        options:
          - chromium
          - firefox
          - webkit

jobs:
  run-ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.2"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: install Playwright browsers
        run: |
          python -m playwright install

      - name: Run tests
        run: |
          echo "Running UI tests in browser: ${{ github.event.inputs.browser }}"
          pytest -m ui --browser-name=${{ github.event.inputs.browser }}
        env:
          URL: ${{ secrets.URL }}
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
          TESTOMATIO: ${{ secrets.TESTOMATIO }}
